### ISSUE TITLE
Preview not compatible with dark themes

### ISSUE THREAD

**Issue by taimila** [vstirbu/vscode-mermaid-preview#1]
Preview is not compatible with dark themes of VS Code. Arrows and texts should be in white on dark background.

See screenshot below:
<img width="1009" alt="mermaid_dark_theme" src="https://cloud.githubusercontent.com/assets/1727790/15286630/bdc73202-1b66-11e6-9ac9-d8b5900d269d.png">

**Comment by vstirbu** [comment]
Thanks for trying the extension and opening this issue. I have overlooked that there might be an issue with dark themes... obviously I'm using light... ;)

The documentation does not mention how to detect programatically if the active theme is light or dark so that I can provide appropriate theme for each case. The API offers limited styling options targeted mainly at text content.

Investigating what is the best way to handle this situation...

**Comment by taimila** [comment]
One simple (but sub optimal) solution is to find a shade of grey that is visible against both backgrounds: dark and light. Or perhaps some other color.

Obviously, "the right way" would be to detect the vs theme and choose mermaid theme accordingly. Let's hope we can find a way to do that.

**Comment by vstirbu** [comment]
There is also the option to have an extension specific workspace setting that controls the stylesheet but that is not optimal either. I've asked a question on this topic on [SO](http://stackoverflow.com/questions/37257911/detect-light-dark-theme-programatically-in-visual-studio-code). Maybe someone will provide the right answer...

**Comment by jrieken** [comment]
@taimila fyi we are working on adding css-variables to the preview part such that you can use with those values. Also, you still have a chance to drop in some requirement ;-) For now, we [have](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/webview.ts#L122): `color`, `background-color`, `font`, and `font-size`

**Comment by vstirbu** [comment]
@jrieken any change to get [isLightTheme](https://github.com/Microsoft/vscode/blob/c82ac047c4f43f738d212c3d6e600180475543d0/src/vs/platform/theme/common/themes.ts#L7) and [getTheme](https://github.com/Microsoft/vscode/blob/c82ac047c4f43f738d212c3d6e600180475543d0/src/vs/workbench/services/themes/common/themeService.ts#L16) exposed on the public API?

**Comment by jrieken** [comment]
I can think of a class we set on the document, ala `<body class="lightTheme">` or `<body class="darkTheme">` such that you can tailor you styles accordingly. I try to avoid exposing them in the API and adding an event for them.

**Comment by vstirbu** [comment]
We are talking about the [body](https://github.com/vstirbu/vscode-mermaid-preview/blob/master/extension.js#L25) of the document that the extension is passing when `vscode.previewHtml`, right?

**Comment by jrieken** [comment]
correct

**Comment by vstirbu** [comment]
I guess this would enable fixing this issue. Any timeline for when this would be available in vscode?

**Comment by jrieken** [comment]
we'll have something end of May

**Comment by vstirbu** [comment]
Waiting the next vscode version and mermaid update to be published to npm to solve this issue...

**Comment by vstirbu** [comment]
@jrieken has this made it to 1.2 release? I wasn't able to spot it in the new features list... I might have missed it as the list was quite long... :)

**Comment by vstirbu** [comment]
this feature works in vscode 1.3 or newer.
