### ISSUE TITLE
Preview appears doubled on screen

### ISSUE THREAD

**Issue by rhyswilkins** [vstirbu/vscode-mermaid-preview#103]
### Expected behaviour

I create a graph, and I should see a representation of it in the Mermaid Preview Pane

```mermaid
graph LR;
    A --> B;
    A --> C;
    C --> D;
    B --> D;
```

### Actual behaviour

I see the graph twice in the Preview pane - one copy moves/zooms, one copy doesn't. They don't stay out of each other's way, meaning that it's sometimes hard to make out what the diagram actually looks like. I'm using Mermaid preview mode, default dark theme for VS code. The only thing is that I'm using WSL, so the file is actually being stored through the WSL Server onto the hard disk of my laptop.

Is there a way to turn the smaller copy off? I'm happy with seeing just one copy, auto-zoomed to fit the Preview window.

![mermaid-preview-graph-doubled](https://user-images.githubusercontent.com/31958930/92749558-1f03e800-f37e-11ea-94b0-cfdce00b196a.png)

**Comment by vstirbu** [comment]
The top-left diagram is the "minimap". You can control the rendering in the settings. Type `mermaid minimap` and uncheck the option.

**Comment by rhyswilkins** [comment]
Hi @vstirbu - that's perfect, thank you. Happy to close, although perhaps this could be added to the documentation.

**Comment by vstirbu** [comment]
Yep. Seems that there is a gap in the docs on the minimap rendering. Expanding soon (#104).
