### ISSUE TITLE
links apparently not sufficiently styled by default for `graph`

### ISSUE THREAD

**Issue by g3o2** [vstirbu/vscode-mermaid-preview#13]
The following code in **vscode version 1.7.1** (Mac OS X Sierra) does not draw the links but only the arrows of the links

```
    ```mermaid
    graph TB;
        A-->B;
        B-->C;
        C-->A;
    ```
```
![screen shot 2016-11-08 at 23 12 11](https://cloud.githubusercontent.com/assets/12123506/20119478/f83e34a8-a608-11e6-8009-3f2b588fba89.png)

It does not matter which color theme is chosen in vscode. It appears to be due to a lack of (default) styling of the links, i.e. probably `stroke` set to `none` or something like that.

![screen shot 2016-11-08 at 23 14 01](https://cloud.githubusercontent.com/assets/12123506/20119528/24fc7824-a609-11e6-92cf-1d699319260d.png)

**Comment by g3o2** [comment]
It would also be more convenient if `fill` be set to `none` by default.

The following links would look weird.

```
    ```mermaid
    graph TB;

      A-->B
      linkStyle 0 stroke:gray,stroke-width:1px;
      click A callback "UCI"
      B-->C
      C-->A
      linkStyle 1 stroke:gray,stroke-width:1px;
      linkStyle 2 stroke:gray,stroke-width:1px;
    ```
```

The fix would be:

```
    ```mermaid
    graph TB;

      A-->B
      linkStyle 0 stroke:gray,stroke-width:1px,fill:none;
      click A callback "UCI"
      B-->C
      C-->A
      linkStyle 1 stroke:gray,stroke-width:1px,fill:none;
      linkStyle 2 stroke:gray,stroke-width:1px,fill:none;
    ```
```

**Comment by g3o2** [comment]
Finally, the arrow-head with its dark gray for dark themes is not very legible. The color code `gray` should be more legible.

**Comment by g3o2** [comment]
It occurs to me that all this may be related to the stylesheets conflict described in #2.

**Comment by vstirbu** [comment]
Thanks for pointing this out. Seems that at least in 1.7 the previewHtml functionality used by the plugin has changed. The styles do not work as expected. Investigating...

**Comment by vstirbu** [comment]
@g3o2 can you post screen captures of what is displayed on your machine. Also the information about your configuration would be useful.

**Comment by g3o2** [comment]
Done.

**Comment by vstirbu** [comment]
Thanks for adding the captures!

Made some initial investigation and so far I have seen on my machine that the rendering of the diagram  does not yield always the same result.

Can you check if you get the correct rendering by following this procedure:
1. open the preview view
2. close it
3. open it again

**Comment by g3o2** [comment]
Voilà, here's what I've done.

1. - 3. as requested

![screen shot 2016-11-09 at 23 15 18](https://cloud.githubusercontent.com/assets/12123506/20156871/7dd08f84-a6d2-11e6-98b2-95553b5d72b9.png)

Then,
4. Click outside of the diagram code.
5. Click back onto the diagram code.

![screen shot 2016-11-09 at 23 15 34](https://cloud.githubusercontent.com/assets/12123506/20156892/8f85519c-a6d2-11e6-87db-43a46f398e71.png)

**Comment by vstirbu** [comment]
yes, exactly the same here. seems that the plugin works well only after the second activation and only for the first rendering, subsequent updates are not rendered correctly.

**Comment by g3o2** [comment]
not quite. try closing the code tab after that, then suddenly the preview works again (for that moment of course)

**Comment by g3o2** [comment]
The said issue has reappeared. Do you have any tests in place to check for past issues ?

**Comment by vstirbu** [comment]
On which vscode version are you?

It is not possible to test what is actually happening inside the viewer component, beyond the input markup.

**Comment by g3o2** [comment]
I'm on 1.11.2.

That's truly a pity, it would be much more convenient to be able to fetch the styles from the output markup. Hmm, how about providing a markdown file with specs that should work ? That way, anyone could perform the tests and notify the issues.

**Comment by agusmba** [comment]
I just tried this plugin for the first time after updating vscode today (there was a reference to this plugin in the release notes).

I'm experiencing this same issue, no arrows visible on the first test diagram (the one shown here).

My vscode is v1.15.1 (windows 32bits build)

In the marketplace, the latest plugin version seems to be 0.0.3 (uploaded a couple days ago), which I don't know how to relate with the releases seen in github (v0.5.0 ?)

Other than that, thanks for the plugin! I'd been longing for this functionality for a while.

**Comment by vstirbu** [comment]
published 0.5.1. The arrow tip is white on my machine for dark theme.

**Comment by agusmba** [comment]
Thanks! Got the 0.5.1 from the market, however I still see no arrow tips...
Maybe there's something wrong on my end.

**Comment by vstirbu** [comment]
Arrows in 0.8.2:
<img width="152" alt="screen shot 2018-01-29 at 22 40 35" src="https://user-images.githubusercontent.com/1288047/35533239-905ecb5c-0545-11e8-9af8-56c1f1747507.png">
