### ISSUE TITLE
arrowhead hardly visible with dark themes

### ISSUE THREAD

**Issue by g3o2** [vstirbu/vscode-mermaid-preview#17]
The arrow-head with its dark gray for dark themes is not very legible. The color code `gray` should be more legible.

for a screenshot, see my second last post from #13

**Comment by vstirbu** [comment]
The plugin uses the forrest and dark stylesheets from mermaid project without any modifications.

If they are not satisfactory I see two ways forward:

1. make a change request to mermaid itself.
2. have a mechanism in this plugin that would allow the user to define additional styles, in the same fashion as the default markdown plugin does.

In any situation, I would not like to maintain stylesheets here.

**Comment by g3o2** [comment]
I think ad 1) is not feasible, for it is not a direct behaviour of mermaid itself but due to the combination of vscode and mermaid.

Then, I also understand your reluctance for maintaining separate stylesheets, which is not a long term solution.. Maybe in the short run you'd just need to punctually override a few CSS setings ? A plugin facility sounds appealing but more like a long term endeavour.

**Comment by tauren** [comment]
Same problem here. Has anyone found a workaround so I don't have to change my theme?

**Comment by vstirbu** [comment]
Arrows in 0.8.2:
<img width="152" alt="screen shot 2018-01-29 at 22 40 35" src="https://user-images.githubusercontent.com/1288047/35533278-b0ae7bb4-0545-11e8-9760-3743cfaea048.png">
