### ISSUE TITLE
customizing link style with any color sets `fill` property to `black` instead of `none`

### ISSUE THREAD

**Issue by g3o2** [vstirbu/vscode-mermaid-preview#18]
example code

```mermaid
graph TB;
    A-->B;
    linkStyle 0 stroke:red;
    B-->C;
    C-->A;
```

see #13, my second post for a screenshot

**Comment by vstirbu** [comment]
Seems like mermaid itself has some problems rendering that snippet (capture from mermaid online editor):

![screen shot 2016-11-25 at 07 13 06](https://cloud.githubusercontent.com/assets/1288047/20615096/c73c2b52-b2de-11e6-9743-462be829b419.png)

**Comment by g3o2** [comment]
Given that mermaid is still under first release development, my guess is that this is only the tip of the iceberg. Want to open an issue at mermaid's git or shall I do that ?

**Comment by vstirbu** [comment]
It would be better if you open it. I'm using only the sequence diagram part of mermaid, so you have better knowledge to follow up this issue already.

**Comment by g3o2** [comment]
Looks like someone has done this before us already: https://github.com/knsv/mermaid/issues/410

**Comment by vstirbu** [comment]
As soon as they publish a new version to npm I'll update the plugin.

**Comment by g3o2** [comment]
Hmm, to be sure I have created this issue separately:
https://github.com/knsv/mermaid/issues/416

**Comment by vstirbu** [comment]
The plugin now depends on mermaid 7.0.0.

Is this still an issue?
