### ISSUE TITLE
Unable to make it work in vs code version 1.7.2

### ISSUE THREAD

**Issue by JCzz** [vstirbu/vscode-mermaid-preview#19]
Hi

I might be missing something, but it does not work for me:

1. created a file .md, & .mmd, & .mermaide

with the following content:

```
```mermaid
sequenceDiagram
  A-->B: Works!
```

```

**Comment by vstirbu** [comment]
In the snippet that you shared the fenced code is not closed, e.g. ``` at the end.

**Comment by vstirbu** [comment]
You could try to reinstall the plugin and see if it corrects the situation. If still persists can you share here the output from the developer console (e.g. Help > Toggle Developer Tools)

**Comment by vstirbu** [comment]
Going to close this as not feedback received. If problem persist, attach a screenshot, details about your machine and reopen. Cheers!

**Comment by JCzz** [comment]
This do work, thanks! I think, I did not note the "select diagram" and set the cursor in the diagram. Thanks, this is really a nice extension.
