### ISSUE TITLE
Arrowheads not showing in diagrams

### ISSUE THREAD

**Issue by rexcfnghk** [vstirbu/vscode-mermaid-preview#2]
I copied the sample diagram from your README but the arrowheads are not showing. My environment:

- Windows 7 64-bit
- VS Code v1.1.1

![capture](https://cloud.githubusercontent.com/assets/2632364/15381133/585fdd74-1daf-11e6-9433-bbc31c979668.PNG)

**Comment by vstirbu** [comment]
I have noticed this behaviour on one of my machines but not on the other. Needs further investigation to get a proper repeatable test env.

**Comment by matthew-beck** [comment]
I don't see the arrow heads either.
This is what I'm using:
- Mac Version 10.10.5
- VSCode Version 1.4.0 (1.4.0)
- Mermaid Preview Version 0.4.0

**Comment by cilerler** [comment]
On same machine, following code does not show the arrows in Visual Studio Code where code below renders it in browser fine.

```text
```mermaid
sequenceDiagram
    Alice ->> Bob: Hello Bob, how are you?
    Bob-->>John: How about you John?
    Bob--x Alice: I am good thanks!
    Bob-x John: I am good thanks!
    Note right of John: Bob thinks a long<br/>long time, so long<br/>that the text does<br/>not fit on a row.

    Bob-->Alice: Checking with John...
    Alice->John: Yes... John, how are you?
`` `
```

```
<!doctype html>
<html>

<head>
    <title>Sample</title>
</head>

<body>
    <div class="mermaid">
sequenceDiagram
    Alice ->> Bob: Hello Bob, how are you?
    Bob-->>John: How about you John?
    Bob--x Alice: I am good thanks!
    Bob-x John: I am good thanks!
    Note right of John: Bob thinks a long<br/>long time, so long<br/>that the text does<br/>not fit on a row.

    Bob-->Alice: Checking with John...
    Alice->John: Yes... John, how are you?
    </div>    
    <div class="mermaid" id="mermaidChart0">
        <svg>
            Chart should end up here
        </svg>
    </div>
    <script src="https://cdn.rawgit.com/knsv/mermaid/0.5.1/dist/mermaid.min.js"></script>
    <script>mermaid.initialize({startOnLoad:true});</script>
</body>

</html>
```

**Comment by vstirbu** [comment]
There is a conflict between mermaid stylesheet and vscode preview stylesheet. As a side note, running the extension in debug mode during development displays the arrow heads fine but not during normal use.
