### ISSUE TITLE
classDiagram rendered all black and not completely

### ISSUE THREAD

**Issue by g3o2** [vstirbu/vscode-mermaid-preview#24]
![screen shot](https://cloud.githubusercontent.com/assets/12123506/22857587/edbd7662-f0a7-11e6-90d1-8d87e352b80c.png)

```mermaid
classDiagram
    Class01 <|-- AveryLongClass : Cool
    Class03 *-- Class04
    Class05 o-- Class06
    Class07 .. Class08
    Class09 --> C2 : Where am i?
    Class09 --* C3
    Class09 --|> Class07
    Class07 : equals()
    Class07 : Object[] elementData
    Class01 : size()
    Class01 : int chimp
    Class01 : int gorilla
    Class08 <--> C2: Cool label
```

vscode 1.9.1, mermaid preview 0.4.3

**Comment by g3o2** [comment]
Seems to be mermaid issue: https://github.com/knsv/mermaid/issues/454

**Comment by vstirbu** [comment]
I'll publish a new version as soon as this is solved upstream

**Comment by vstirbu** [comment]
Seems that 0.8.2 renders correctly the diagram with both themes. Closing now.

<img width="1740" alt="screen shot 2018-01-29 at 22 35 57" src="https://user-images.githubusercontent.com/1288047/35533055-faf23126-0544-11e8-9ccf-846b2a097c90.png">
<img width="1740" alt="screen shot 2018-01-29 at 22 36 21" src="https://user-images.githubusercontent.com/1288047/35533060-fdfcb170-0544-11e8-83ab-7b95c385a278.png">
