### ISSUE TITLE
Support for awesome

### ISSUE THREAD

**Issue by luebken** [vstirbu/vscode-mermaid-preview#32]
I like to style my graphs with icons from font-awesome. https://knsv.github.io/mermaid/#basic-support-for-fontawesome

Previewing fontawesome in VSCode would be awesome. ;-)

**Comment by vstirbu** [comment]
Adding font awesome  can be done although it might affect the live editing. Maybe add it behind a configuration flag so that it does not affect people that do not use icons in their diagrams.
