### ISSUE TITLE
integrate plugin with markdown preview

### ISSUE THREAD

**Issue by agusmba** [vstirbu/vscode-mermaid-preview#37]
I'm not sure how to ask this. It seems that the latest vscode version supports this integration:

https://code.visualstudio.com/updates/v1_15#_support-for-markdown-preview-plugins

In those release notes another mermaid plugin is showing this integration.

Would it make sense to add this integration here also?

Thanks!

**Comment by vstirbu** [comment]
definitely, this is a must! I was short on time for this one... :)
