### ISSUE TITLE
Not open preview

### ISSUE THREAD

**Issue by aymone** [vstirbu/vscode-mermaid-preview#4]
`No handler found for the command: 'extension.previewMermaidDiagram'. An extension might be missing an activation event.`

Any dependency to show previews?

**Comment by vstirbu** [comment]
I have noticed this behaviour and in my case I have fixed this particular error by uninstalling and installing the extension. Which version you have now installed?

**Comment by aymone** [comment]
v0.3.3
 I have install / uninstall / installed again... 
I using vscode on ubuntu 16.04

**Comment by vstirbu** [comment]
is there any `node_modules` directory under `.vscode/extensions/vstirbu.vscode-mermaid-preview-0.3.3` in your home directory?

the only dependencies are lodash and mermaid and both are pure javascript, so no native compilation is required.

**Comment by aymone** [comment]
Yeap, have this directory... vstirbu.vscode-mermaid-preview-0.3.3

**Comment by vstirbu** [comment]
Is this still an issue?
