### ISSUE TITLE
[request] Add label support for alt and loop

### ISSUE THREAD

**Issue by asampal** [vstirbu/vscode-mermaid-preview#41]
It would be nice to have cases and loops show the name provided in the source.

**Comment by vstirbu** [comment]
Can you provide more details about the situation? Is this happening  in mermaid preview mode or in the build-in markdown viewer? Also an example and a screenshot would be nice. Thanks!

**Comment by asampal** [comment]
Sure, you can see the way alt and loop should look when labeled, [here](https://mermaidjs.github.io/mermaid-live-editor/#/edit/c2VxdWVuY2VEaWFncmFtCmZvby0-PmJhcjogaGVsbG8KYWx0IGdvb2QKICBiYXItPj5mb286IGV2ZXJ5dGhpbmcncyBjb29sCmVsc2UgYmFkCiAgYmFyLT4-Zm9vOiB1aCBvaAplbmQKbG9vcCBrZWVwIGRvaW5nIGl0IQogIGZvby0-PmJhejogZG8gaXQhICAgCmVuZAo)

![image](https://user-images.githubusercontent.com/281639/30769281-fd451004-9fe3-11e7-9137-0263ef5fd936.png)

**Comment by vstirbu** [comment]
Ok, so for this diagram:

```mermaid
sequenceDiagram
foo->>bar: hello
alt good
  bar->>foo: everything's cool
else bad
  bar->>foo: uh oh
end
loop keep doing it!
  foo->>baz: do it!   
end
```

I'm getting the following results:

![screen shot 2017-09-23 at 6 35 37](https://user-images.githubusercontent.com/1288047/30769831-ce1c4284-a029-11e7-8989-ef23fbc22576.png)

![screen shot 2017-09-23 at 6 37 07](https://user-images.githubusercontent.com/1288047/30769832-d4c0d7ee-a029-11e7-8c5f-8bd598cd25bf.png)

The caption text is black in the dark theme.

**Comment by asampal** [comment]
Yup, that's what I'm using - I guess I should've looked harder. Could this be changed?

**Comment by vstirbu** [comment]
I'll notify upstream.

**Comment by bnacey** [comment]
Has there been any progress on this issue?

**Comment by vstirbu** [comment]
The solution should come from mermaid itself due to the way it handler the CSS.

You might speed things up by commenting on the mermaid issue referenced above.

**Comment by DesHorsley** [comment]
Hi @vstirbu looks like the upstream issue has been closed, will that solution filter down to the plugin?

**Comment by vstirbu** [comment]
The issue was not completely fixed upstream, but the api has been extended to allow custom CSS. In the end the custom css for dark theme should be incorporated upstream, although for now we do it here.

```css
.loopText tspan { 
   fill: inherit;
}
```
