### ISSUE TITLE
Better UX for wide diagrams

### ISSUE THREAD

**Issue by vstirbu** [vstirbu/vscode-mermaid-preview#44]
Wide diagrams are scaled down in a way that makes reading the text hard.

With version 0.8.0 I've tried to add pan and zooming support to address this problem. The library included in that release was [svg-pan-zoom](https://github.com/ariutta/svg-pan-zoom), which had some side effects related to scaling on retina displays, so I had to revert. Version 0.8.1, removed the pan and zoom feature and allowed the flowcharts to use as wide area as they need. Version 0.8.2 added a minimap that renders in the upper left corner a smaller version of the diagram.

([panzoom](https://github.com/anvaka/panzoom) seems to integrate better with mermaid but there are still issues related to integrating it with the previewHTML component of vscode.)

I would appreciate ideas to improve this situation.

**Comment by g3o2** [comment]
#64 could be a solution for that.

**Comment by GaryBer** [comment]
Need some ability to zoom or scroll. Very long diagrams become too scaled to read.

**Comment by GaryBer** [comment]
I fixed my vertical zoom issue by changing the line:
https://github.com/vstirbu/vscode-mermaid-preview/blob/298a7a9a4d51b7ec728e2e0fe64899ab48bbbaf3/extension.js#L50

From:
```
<div id="diagram" class="mermaid" style="height: 100vh"></div>
```

To:
```
<div id="diagram" class="mermaid" style="height: 100%; padding: 15px; overflow: auto;"></div>
```

**Comment by GaryBer** [comment]
Adding simple zoom ability that does not adjust the bounding box.

```
<div style="position: fixed; top: 10px; right: 10px; z-index: 100; display: block; font-weight: 700; -webkit-text-stroke-width: 1px; -webkit-text-stroke-color: black; font-size: 16px; line-height: 16px; user-select: none; color: #fff;">
  <div id="zoom-in" style="cursor: pointer; padding: 7px;">&plus;</div>
  <div id="zoom-out" style="cursor: pointer; padding: 7px;">&minus;</div>
</div>

<script>
  const zoomIn = document.getElementById('zoom-in');
  const zoomOut = document.getElementById('zoom-out');
  const diagramView = document.getElementById('diagram');

  let currentScale = 1;
  
  function setDiagramScale(scale) {
    diagramView.style.transform = 'scale(' + scale + ')';
  }

  setDiagramScale(currentScale);

  zoomIn.addEventListener('click', () => {
    currentScale+=0.25;
    setDiagramScale(currentScale);
  });

  zoomOut.addEventListener('click', () => {
    currentScale-=0.25;
    setDiagramScale(currentScale);
  });
</script>
```

**Comment by GaryBer** [comment]
Fixed the scroll bug that I was having.

```
const diagramContainer = document.getElementById('diagram-container');

    let currentScrollTop = 0;

    function setDiagramScrollTop(value) {
      window.scrollTo({
        top: value
      });
    }

    document.addEventListener('scroll', () => {
      const value = parseInt(window.scrollY);
      if (value) {
        currentScrollTop = value;
      }
    });
```

Just add `setDiagramScrollTop(currentScrollTop);` to the end of the window message event listener.

```
window.addEventListener('message', event => {
        const message = event.data;

        minimap.textContent = message.diagram;
        minimap.removeAttribute('data-processed');
        
        diagram.textContent = message.diagram;
        diagram.removeAttribute('data-processed');

        mermaid.init();

        setDiagramScrollTop(currentScrollTop);
});
```
