### ISSUE TITLE
how to config ,giving a sample.

### ISSUE THREAD

**Issue by ardorleo** [vstirbu/vscode-mermaid-preview#46]
how to config ,giving a sample.

**Comment by vstirbu** [comment]
what do you want to configure?

**Comment by ardorleo** [comment]
Hi:
     my problem is the config not successful.



------------------ 原始邮件 ------------------
发件人: "Vlad Știrbu";<notifications@github.com>;
发送时间: 2017年12月8日(星期五) 下午5:58
收件人: "vstirbu/vscode-mermaid-preview"<vscode-mermaid-preview@noreply.github.com>;
抄送: "ardorleo"<ardorleo@foxmail.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vstirbu/vscode-mermaid-preview] how to config ,giving a sample.(#46)




what do you want to configure?

**Comment by vstirbu** [comment]
this is how I use your sample configuration:
![screen shot 2017-12-08 at 21 50 37](https://user-images.githubusercontent.com/1288047/33782634-23d2affa-dc62-11e7-92a0-9d4851c8d3da.png)

**Comment by vstirbu** [comment]
reopen if still a problem
