### ISSUE TITLE
Convert markdown to pdf

### ISSUE THREAD

**Issue by cblomart** [vstirbu/vscode-mermaid-preview#47]
When using "Convert Markdown to pdf" the memaid schema used are not rendered. Only the memaid text content is shown in the pdf.

**Comment by cblomart** [comment]
Hello, i use another extension effectively:
https://github.com/yzane/vscode-markdown-pdf

**Comment by vstirbu** [comment]
Can you add a screenshot to have a record of how the diagram looks like when converted to pdf?

**Comment by cblomart** [comment]
In vscode:

![image](https://user-images.githubusercontent.com/3999494/35304416-bdc18878-0095-11e8-8a98-e448b04b2185.png)

On pdf [mermaid.pdf](https://github.com/vstirbu/vscode-mermaid-preview/files/1657851/mermaid.pdf)

**Comment by vstirbu** [comment]
This plugin interacts with the built-in markdown preview using the [markdown extensions](https://code.visualstudio.com/docs/extensionAPI/api-markdown). Looks like the pdf converting plugin does not implement the equivalent functionality therefore the fenced mermaid diagram is not actually rendered. This should be brought to the attention of the plugin developer.

**Comment by cblomart** [comment]
Should be done as i mentionned the issue i opened with them.

**Comment by FantasyLeo** [comment]
look forward to
