### ISSUE TITLE
[request] Handles more tags around mermaid code, like HUGO shortcodes.

### ISSUE THREAD

**Issue by SR-G** [vstirbu/vscode-mermaid-preview#48]
Mermaid can be wired for examples with HUGO shortcodes (and inclusion of mermaid files in the HUGO's template). Sadly, the vscode-mermaid-preview does not work anymore in this situation, as the mermaid code is enclosed in a tag not known (yet) by the vscode extension.

For example, i'm using these tags : 

``
{{<mermaid align="left">}}
{{</mermaid>}}
``

The proposal would be to either take in account that kind of tags, either to allow to have customizable tags in a global vscode-mermaid-preview configuration.

**Comment by SR-G** [comment]
Yes, basically that's it.

HUGO is a templating system (static generator) allowing to convert markdown to HTML.
By default, HUGO does not know anything about mermaid, but can easily be extended with "shortcodes" - that are just a small template linked to a HTML entry name (like in the example above). The shortcode name is customizable.

Handling the token as in my example would fit my need, but maybe it's better to make something more generic that would allow to handle any other names, whatever the situation is (HUGO shortcodes, or anything else).

**Comment by vstirbu** [comment]
can you check if the following regex captures correctly the diagram https://regex101.com/r/iAmzA9/6?

**Comment by SR-G** [comment]
Yes, it seems fine like this, the output result has the expected layout.

**Comment by vstirbu** [comment]
do hugo templates (in common use) have other extensions than .html?
