### ISSUE TITLE
Preview Mermaid Diagram from .mmd fails

### ISSUE THREAD

**Issue by cnelsonakgov** [vstirbu/vscode-mermaid-preview#51]
### Expected behavior

```mermaid
sequenceDiagram
  participant A as Azure Application
  participant E as ESB
  Note left of A: User session <br> established
  A->>E: Request REST endpoint
  A-->>E: Provide Basic Auth Token
  E->>E: Check token against DHSS AD
  E->>A: Return JSON payload
  Note right of E: Channel between <br> Azure and ESB <br> secured with Basic <br> Auth over TLS
```

I save a Mermaid diagram as a .mmd file. When I try to `Review Mermaid Diagram` I see the preview

### Actual behavior

I save Mermaid diagram a .mmd file. When I try to `Review Mermaid Diagram` I get and error `command 'extension.previewMermaidDiagram' not found`.  Preview works fine for the same diagram when embedded in a markdown diagram.

Include:
  * Screenshot: 
     * ![image](https://user-images.githubusercontent.com/36310962/40206897-5d2bf2d0-59de-11e8-8eda-be147b496792.png)
     * ![image](https://user-images.githubusercontent.com/36310962/40206962-97a0116c-59de-11e8-8f60-38e905ead37b.png)
   * Preview mode: Mermaid
   * Theme used: dark

**Comment by vstirbu** [comment]
I'm not able to replicate the behaviour on my side. Got the following result:
![screen shot 2018-05-18 at 8 28 25](https://user-images.githubusercontent.com/1288047/40217436-5f6203fe-5a75-11e8-8645-d64a3665366f.png)

Can you reinstall the plugin? Is there more info in the console (Help > Toggle Developer Tools)?

**Comment by cnelsonakgov** [comment]
I reinstalled the plugin, but it still behaves in the same manner. The Developer Tools Console has quite a bit of detail but I'm not sure what would be helpful. Here is a quick snippet:
![image](https://user-images.githubusercontent.com/36310962/40253229-82857f08-5a8b-11e8-9f31-cbc4d70cba7f.png)

**Comment by vstirbu** [comment]
Seems that there is a parsing error in the loads file that manifests on Windows.

Is there anything in the console when you see the mermaid diagram in a markdown file? When you try to visualise the .mmd file after the markdown does it work?

**Comment by cnelsonakgov** [comment]
Looks like there was an error on the disk -- corrupted files in the the extension folder. Uninstalling it was not enough; I had to go also go into the `~/.vscode/extensions/` folder and remove the directory for the extension. Reinstalled and everything seems to work again. Thanks for your assistance.
