### ISSUE TITLE
Syntax Highlighting in Editor Window?

### ISSUE THREAD

**Issue by jplew** [vstirbu/vscode-mermaid-preview#54]
### Question

Firstly, nice extension, it works perfectly.

I know this goes beyond the scope of this extension, but can you recommend any solution for  syntax highlighting? I'm tired of looking at plain white on black. Are there any Mermaid language extensions to color my markup?

<img width="937" alt="image" src="https://user-images.githubusercontent.com/462836/41747267-32051560-7562-11e8-87a9-1815c125e6a7.png">

**Comment by vstirbu** [comment]
No existing solutions that I'm aware of.

I would love to have this feature implemented but I'm not able to allocate time for this. Nevertheless, I would welcome contributions!

**Comment by jplew** [comment]
I think this is a good starting point:
https://code.visualstudio.com/docs/extensionAPI/language-support
https://code.visualstudio.com/docs/extensions/example-language-server

No promises but I can try to dedicate some time in the next while.

**Comment by vstirbu** [comment]
maybe this is also relevant as most likely the mermaid diagram is embedded in another language (e.g. markdown): https://github.com/mjbvz/vscode-lit-html

**Comment by bpruitt-goddard** [comment]
I took a stab at this and created a separate extension handling the highlighting, but it isn't yet fully complete. It supports graph and sequence diagrams in markdown fenced code. I can merge it into this project if desired, either in its current incomplete state or once it is further along.

https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight

Example:
<img src="https://raw.githubusercontent.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/master/images/graph.png" alt="Graph Screenshot" width="500">

**Comment by Trefex** [comment]
Can you also make it for mmd extensions so one does not need to fence?

**Comment by vstirbu** [comment]
@bpruitt-goddard Lets keep them separated at this time. I do not have enough spare cycles to handle publishing process, and that will slow you down.

I've added a link to your plugin in the README. That will help with discovery.

**Comment by bpruitt-goddard** [comment]
@vstirbu Thanks! That makes sense. There are a few bugs as it is a rough implementation, so I'll probably be publishing a few updates.

@Trefex I [added an issue](https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/issues/10) to support raw mmd files. I'll try tackling that next.

**Comment by vstirbu** [comment]
@bpruitt-goddard maybe is better to merge the syntax highlighting here already. Just make the pull request... Thanks!

**Comment by ppseprus** [comment]
guys! awesome extensions! both of them! however, the current version of the preview messes up the syntax highlight. I have syntax highlight thanks to @bpruitt-goddard, but as soon as I enable the preview extension made by @vstirbu, the highlight is gone...
do you guys know about this?

**Comment by vstirbu** [comment]
<img width="1117" alt="screenshot 2019-02-04 at 8 15 28" src="https://user-images.githubusercontent.com/1288047/52192912-1586d580-2855-11e9-8880-6742308080fa.png">

Works on my side fine. Can you share some details about your environment so that others can try to replicate? Thanks!

**Comment by vstirbu** [comment]
@ppseprus moved this into separate issue

**Comment by ppseprus** [comment]
Thanks!
