### ISSUE TITLE
Unable to use custom mermaid settings

### ISSUE THREAD

**Issue by bzitzow** [vstirbu/vscode-mermaid-preview#55]
### Expected behaviour

In the workspace settings, I have configured:
```json
{
    "mermaid": {
        "sequenceDiagram": {
            "mirrorActors": false,
            "width": 250
        }
    }
}
```

### Actual behaviour

VSCode reports: "Unknown configuration setting" on the string "mermaid". The settings are not applied.

**Comment by vstirbu** [comment]
Cannot replicate the error. I have used your example configuration in both user and workspace settings and the diagram is generated correctly.

Please provide more information about your environment.

**Comment by davingreen** [comment]
I'm also having this same issue. Settings are not working in User or Workspace settings; shows "Unknown configuration setting".

![image](https://user-images.githubusercontent.com/11077948/48649474-b2597580-e9c0-11e8-987c-5459e5e0ec5e.png)

Mermaid Preview v0.10.1

VS Code Info:
Version: 1.29.1 (user setup)
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

**Comment by vstirbu** [comment]
Lets explore further this issue in #57.

**Comment by alexwall** [comment]
Version Mermaid-Preview `0.12.0`

I've tried to set the theme 


<img width="550" alt="image" src="https://user-images.githubusercontent.com/316469/58009181-2995d080-7aee-11e9-80d1-00b96f2e2263.png">


Only one setting is available. See code completion `mermaid.arrowMarkerAbsolute` 

<img width="857" alt="image" src="https://user-images.githubusercontent.com/316469/58009252-50540700-7aee-11e9-8da3-a513aae184bb.png">

**Comment by vstirbu** [comment]
There are three issues in this thread:

1. the custom theme is not rendered
1. the docs are not clear
1. the settings completion shows only one property

For 1 follow the example in the test [folder](https://github.com/vstirbu/vscode-mermaid-preview/tree/master/test/fixtures/custom-theme). For 2 or 3 open separate issues.

Thanks!

**Comment by alexwall** [comment]
I guess the problem, that I use mermaid in markdown files

Preview as mermaid only (on the right):

<img width="909" alt="image" src="https://user-images.githubusercontent.com/316469/58013466-f0ae2980-7af6-11e9-9eec-def0fe539682.png">

vs preview as a part of a markdown preview (on the left) : 

<img width="946" alt="image" src="https://user-images.githubusercontent.com/316469/58013574-24894f00-7af7-11e9-844f-b7315b8c5449.png">

So it seems, that the customisation is not working for markdown embedded previews. 
I can create a issue for this if you like

**Comment by vstirbu** [comment]
The issue with customising the theme in the markdown preview is that this extension is not the only one in town that converts the the fenced code into the diagram (e.g. https://github.com/mjbvz/vscode-markdown-mermaid).

I have not tried if both plugins are installed. Not sure what is the best way forward. You could open a issue and I'll try to get @mjbvz's opinion...

**Comment by alexwall** [comment]
Ok I've created this issues: https://github.com/vstirbu/vscode-mermaid-preview/issues/76
