### ISSUE TITLE
Flickering and scroll bar stepping

### ISSUE THREAD

**Issue by leidegre** [vstirbu/vscode-mermaid-preview#56]
### Expected behaviour

No flickering, and no scroll position change. 

### Reproduce

To reproduce (doesn't matter what diagram) I just open any markdown in preview mode and type a space anywhere, every other space or so the result is somewhat different and the scroll position will move up 1 line.

### Actual behaviour

The diagram is rendered with different colors depending on whether the file is fully saved to disk or not when looking at the markdown preview. It's also switches between different colors as I'm typing. The scroll position moves up 1 line when this happens.

I'm using the Monokai Pro Dark Theme, might be an issue here. I also have a custom editor style on top of this.

```
{
  "editor.tokenColorCustomizations": {
    "textMateRules": [
      {
        "scope": ["comment"],
        "settings": {
          "fontStyle": ""
        }
      }
    ]
  }
}
```

### Edit:

This is a minor inconvenience, all in all, I really like the extension.

**Comment by vstirbu** [comment]
Can you make a screen capture and share it here? Thanks!

**Comment by leidegre** [comment]
![scrolling](http://g.recordit.co/msdDTkwfM4.gif)

![flickering](http://g.recordit.co/5UkXeuc4aL.gif)

**Comment by leidegre** [comment]
@vstirbu all I'm doing is pressing the spacebar, nothing else.

**Comment by leidegre** [comment]
@vstirbu I do not have the `bierner.markdown-mermaid` installed. I'll experiment with the other preview mode.

**Comment by vstirbu** [comment]
Any updates?
