### ISSUE TITLE
Update to newest Mermaid version

### ISSUE THREAD

**Issue by fmakowski** [vstirbu/vscode-mermaid-preview#6]
Hi there!
I have recently started using your extension. Unfortunately, I cannot easily escape some characters (i.e. ":" cannot be escaped in any way), so I have decided to look for a solution. It seems to be resolved on the Mermaid side though (in version 0.5.2) - which led me to check if the extension is using the newest Mermaid version possible.

It looks like it does not, so my question is: is there any way to update it? Should this be done on the code side or I can do that manually somehow?

Best regards!
Filip

**Comment by vstirbu** [comment]
Thanks for finding the extension useful!

This is strange as the version used in this plugin is `6.0.0`, the latest mermaid version published in [npm registry](https://www.npmjs.com/package/mermaid). So, it should already have all the features present in `0.5.2`.

I'll do a bit of investigation myself...

**Comment by vstirbu** [comment]
I have tried to use `:` in labels and notes and it works as expected. The only place where it seems to fail is in the `participant`.

Can you post here an example of what you try to achieve and what would be the expected result?

**Comment by fmakowski** [comment]
Here you can see the entity code being changed into the colon symbol itself: 

![screenshot_20161004_181751](https://cloud.githubusercontent.com/assets/2910034/19082673/6fc047fc-8a5f-11e6-89c9-cef758dd7f9d.png)

Here is the changelog file of the currently installed Mermaid, and it points to version 0.4.0:

![screenshot_20161004_182046](https://cloud.githubusercontent.com/assets/2910034/19082697/867b3394-8a5f-11e6-9fc0-2cbaf0cb99fb.png)

**Comment by vstirbu** [comment]
That gives an invalid syntax at http://knsv.github.io/mermaid/live_editor/
![screen shot 2016-10-04 at 19 37 17](https://cloud.githubusercontent.com/assets/1288047/19083265/24f31028-8a6a-11e6-8316-664293e0e698.png)

**Comment by fmakowski** [comment]
@vstirbu right... so you think this is still not solved on the library side? And also, do you have any idea how to explain that my CHANGELOG points to old version?

**Comment by vstirbu** [comment]
Seems that they have not updated the [CHANGELOG](https://github.com/knsv/mermaid/blob/master/CHANGELOG.md) in a long time.

Yes, the issue is in the library. You might want to open an issue with mermaid to get more info about why it is not working as expected...

**Comment by fmakowski** [comment]
Ahh ok, my bad. Sorry for reporting the issue then and thank you for your help!

Best regards,
Filip

**Comment by vstirbu** [comment]
ping back when you have updates! :)
