### ISSUE TITLE
Plugin disables mermaid highlighting in mmd files

### ISSUE THREAD

**Issue by vstirbu** [vstirbu/vscode-mermaid-preview#60]
It seems that the plugin disables the syntax highlighting when diagrams are in separate files.

When the Preview extension is disabled, the syntax highlight works
![syntax ok](https://user-images.githubusercontent.com/1323285/52200197-62c07280-2868-11e9-98e9-87ae1f15c741.png)

When the Preview extension is enabled, the syntax highlight is gone
![syntax not ok](https://user-images.githubusercontent.com/1323285/52200249-8c799980-2868-11e9-8ed7-2175984dede4.PNG)

Regards!

_Originally posted by @ppseprus in https://github.com/vstirbu/vscode-mermaid-preview/issues/54#issuecomment-460183076_

**Comment by GaryBer** [comment]
https://github.com/bpruitt-goddard/vscode-mermaid-syntax-highlight/issues/21

**Comment by vstirbu** [comment]
thanks for the update!
