### ISSUE TITLE
Allow applying custom themes.

### ISSUE THREAD

**Issue by Apollo3zehn** [vstirbu/vscode-mermaid-preview#63]
It would be great if this extension would allow applying custom themes as suggested in [this post](https://github.com/mermaidjs/mermaid.cli/pull/24#issuecomment-373402785). My aim is to have a similar appearance in vscode like the graph I created in the [online editor](https://mermaidjs.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZ3JhcGggVERcbiAgICBEQShcImZhOmZhLWVsbGlwc2lzLWggICBBREMgKHJhdylcIilcbiAgICBQVChmYTpmYS1jaGFydC1saW5lIFBvc2l0aW9uIFRyYWNrZXIpXG4gICAgRkkoZmE6ZmEtZmlsdGVyIEZpbHRlcilcbiAgICBGVChmYTpmYS1yYW5kb20gRm91cmllciBUcmFuc2Zvcm0pXG4gICAgQVN7QVhJLTQgU3RyZWFtIFN3aXRjaH1cbiAgICBSVyhSQU0gd3JpdGVyKVxuICAgIFJBTShmYTpmYS1tZW1vcnkgUkFNKVxuXG4gICAgc3ViZ3JhcGggUHJvY2Vzc2luZ1xuICAgICAgICBEQSAtLT4gfEFYSS00IFN0cmVhbXwgUFRcbiAgICAgICAgUFQgLS0-IHxBWEktNCBTdHJlYW18IEZJXG4gICAgICAgIEZJIC0tPiB8QVhJLTQgU3RyZWFtfCBGVFxuICAgIGVuZFxuXG4gICAgREEgLS0-IHxBWEktNCBTdHJlYW18IEFTXG4gICAgUFQgLS0-IHxBWEktNCBTdHJlYW18IEFTXG4gICAgRkkgLS0-IHxBWEktNCBTdHJlYW18IEFTXG4gICAgRlQgLS0-IHxBWEktNCBTdHJlYW18IEFTXG5cbiAgICBBUyAtLT4gfEFYSS00IFN0cmVhbXwgUldcbiAgICBSVyAtLT4gfEFYSS00fCBSQU1cbiIsIm1lcm1haWQiOnsidGhlbWUiOm51bGwsInRoZW1lQ1NTIjoiI3N1YkdyYXBoMCB7IGZpbGw6d2hpdGUgfSAgLm5vZGUgPiByZWN0IHsgc3Ryb2tlOiMwMEJDRDQ7fSAuY2x1c3RlciA-IHJlY3QgeyBzdHJva2U6I0U2MUU2Mzt9IC5lZGdlTGFiZWwgeyBkaXNwbGF5OmJsb2NrO29wYWNpdHk6MTtiYWNrZ3JvdW5kOndoaXRlO2JvcmRlci1yYWRpdXM6NXB4O3BhZGRpbmc6MHB4IDEwcHg7fSAubm9kZSB7IGZpbGw6IGF6dXJlIH0gcGF0aCB7IHN0cm9rZS13aWR0aDogMS41cHg7IHN0cm9rZTogIzAwQkNENH0gcG9seWdvbnsgc3Ryb2tlLXdpZHRoOiAxLjVweDsgc3Ryb2tlOiAjMDBCQ0Q0fSB0ZXh0IHsgZmlsbDpyZ2JhKDAsIDAsIDAsIDAuNjUpOyBmb250LXNpemU6IDIycHg7IHRyYW5zZm9ybTogdHJhbnNsYXRlWCgxNTBweCkgdHJhbnNsYXRlWSg0MHB4KSB9IiwiZmxvd2NoYXJ0Ijp7ImN1cnZlIjoibGluZSJ9fX0).

 If I understand [these ](https://github.com/vstirbu/vscode-mermaid-preview/blob/8b98fd0a89aaa3686a1dbaf584a7d3adffb80ca6/content-provider.js#L49-L59) lines correctly, the configuration is loaded but unfortunately the fields "theme" and "themeCSS" are overriden. To keep flexibility I would like to suggest to only override these settings if they are not present in the previously loaded config.

**Comment by vstirbu** [comment]
Seems like a sensible approach to apply the `theme` and `themeCSS` if they are available in the loaded configuration. In this case the user would be fully responsible for the end result (e.g. rendering). Would that be ok?

**Comment by Apollo3zehn** [comment]
If the new behavior is well documented, I think it is a feasable approach.

**Comment by vstirbu** [comment]
Also one option to use [@uifabric/merge-styles](https://www.npmjs.com/package/@uifabric/merge-styles) and merge the loaded styles into the defaults (e.g. the current ones). With this approach, at least, the customisation starts from a sane state.

**Comment by Apollo3zehn** [comment]
I had problems overriding defaults, even if I use !important. So if in a config the theme is set to `"theme": null` (or any other custom theme), there should be no defaults. If - on the other hand - there is no `"theme:"` but only `"themeCSS":` defined, then I think [@uifabric/merge-styles](https://www.npmjs.com/package/@uifabric/merge-styles) is a good idea.

**Comment by vstirbu** [comment]
Ok! Lets leave the user in full control for now. If there is demand to do the merge, it can be done later with merge-styles
