### ISSUE TITLE
improve mermaid preview window layout behaviour

### ISSUE THREAD

**Issue by g3o2** [vstirbu/vscode-mermaid-preview#64]
### Expected behaviour

Allow mermaid preview (based on `.mmd` files) window to be put anywhere according to the vscode layout specifications (left, right, bottom, top, etc.).

### Actual behaviour

When one drags and drops an existing mermaid preview window to a different layout structure (e.g. top-down split instead of left-right split), with a mermaid `.mmd` file being previewed, the follow error is thrown by vscode:

> Unable to open `Mermaid Preview`: ModelService: Cannot add model because it already exists!.

VS code 1.30.2 (dark theme).

**Comment by vstirbu** [comment]
fixed by #67
