### ISSUE TITLE
Export not working (or not sure)

### ISSUE THREAD

**Issue by clebio** [vstirbu/vscode-mermaid-preview#69]
### Expected behaviour

1. Run mermaid export
1. see my file, or ... _something_.

### Actual behaviour

1. Run mermaid export (cmd-ctrl-p)
1. [nothing happens]

Where does it export to? Assuming `cwd`, it is not working. No log messages (despite checking mermaid export debug" in settings). 

I searched issues, and this project's readme (doesn't contain the word "export"). Possibly related to #57 (in that I _don't_ seem to have a working config).

**Comment by vstirbu** [comment]
This plugin does not support exporting the diagrams, only preview. Do you have other Mermaid plugins installed?

**Comment by clebio** [comment]
Hey, thanks. What do you mean by "export preview" -- does it export SVG, PNG, ... ? Maybe just adding a note about the export capability in the README would help.

**Comment by vstirbu** [comment]
Export means `save` in this context. There is already an open ticket tracking that. Closing this one in favour of #5.
