### ISSUE TITLE
On Windows participants are shown separately in sequence diagram

### ISSUE THREAD

**Issue by sjamesexamsoft** [vstirbu/vscode-mermaid-preview#70]
### Expected behaviour
Using participant key word to order actors in sequence diagram.
On Windows each participant creates a separate "actor" with same name as existing actor in the message sequence.

```mermaid
sequenceDiagram
    participant John
    participant Mary
    John->>Mary: call
    Mary->>John: answer
```

### Actual behaviour

Include:
   * Screenshot
   * Preview mode: Mermaid
   * Theme used: default
<img width="624" alt="Screenshot 2019-04-11 09 03 37 (2)" src="https://user-images.githubusercontent.com/36855514/55963806-20852a00-5c39-11e9-9fbf-a91cac915ac7.png">

**Comment by vstirbu** [comment]
Do you get the same in the [online editor](https://github.com/mermaidjs/mermaid-live-editor) using Chromium-derived browser?

**Comment by sjamesexamsoft** [comment]
No, and I don't see this behavior on Mac VS Code.
