### ISSUE TITLE
Does not render

### ISSUE THREAD

**Issue by tgdn** [vstirbu/vscode-mermaid-preview#72]
New file with mermaid code within it > "Preview on Mermaid" > opens the preview pane and I put my cursor on it, but nothing happens as can be seen in the screenshot below.

Tried multiple times with different code.

The dev console logs:

```
[Embedded Page] Uncaught TypeError: Cannot read property 'setAttribute' of null
webviewElement.ts:392
```

macOS Mojave
VS Code: Version 1.33.1 (1.33.1)
Mermaid Preview: v0.11.2

### Expected behaviour

```mermaid
graph TD
    Start --> Stop
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/480050/56122094-817a6e00-5f69-11e9-9418-6af85368f53d.png)

**Comment by vstirbu** [comment]
You have to use `.mmd` file extension id the diagram is not embedded in a markdown document.

**Comment by tgdn** [comment]
Still doesn't work

**Comment by vstirbu** [comment]
What do you get in the log after adding the mmd extension? Alternatively can you see the diagram if the diagram is embedded in a markdown document?

**Comment by tgdn** [comment]
When I use the mdd extension I have the same exception:

```
[Embedded Page] Uncaught TypeError: Cannot read property 'setAttribute' of null
```

However, when I embed the mermaid code within markdown it works, but most then the text cannot be seen as it's dark on dark.

![image](https://user-images.githubusercontent.com/480050/56270678-a1876a00-60ee-11e9-929a-2eda6f9f5e8a.png)

**Comment by vstirbu** [comment]
The extension for stand alone mermaid is `mmd`. You mentioned `mdd`. Is that a typo?

The styling comes from mermaid. The plugin does not change that. If there are any issues with the styling (e.g. not visible with dark theme), you should bring it to their attention as most likely the problem exists in other environments where dark mode is used.

Alternatively, you have the option to provide a [custom theme](https://github.com/vstirbu/vscode-mermaid-preview#custom-theme).

**Comment by tgdn** [comment]
Yes that's a typo sorry. .mmd is the extension I tried which gave a blank preview.

Thank you I'll just use markdown with a different theme.
