### ISSUE TITLE
Text overflows on mermaid graphs

### ISSUE THREAD

**Issue by 4lph4-Ph4un** [vstirbu/vscode-mermaid-preview#77]
### Expected behaviour

```mermaid
graph LR
D(Dispatcher)-->S1(Saga)
D(Dispatcher)-->R(Reducer)
S1(Saga)-->G(Generator)
R(Reducer)-->S2(Store)
G(Generator)-->R(Reducer)
```

### Actual behaviour

![vscmpissue](https://user-images.githubusercontent.com/25401310/58378963-4a09d300-7fa5-11e9-943f-24ea5dc028e0.png)

**Comment by vstirbu** [comment]
I cannot replicate the rendering. Can you share details about your OS, vscode version that can help others identify the root cause?

**Comment by 4lph4-Ph4un** [comment]
Ah, oh course! My apologies! 

Windows 10, VSCode 1.34.0

**Comment by mrtzcspr** [comment]
Hi,
at least on Windows 10 with latest vscode and latest vscode-mermaid-preview I can reproduce the issue by setting a zoom level below 100% for vscode (Menu Selection: View --> Appearance --> Zoom Out).

When the zoom level is reset  (Menu Selection: View --> Appearance --> Reset Zoom) it works again without overflows when the mermaid preview is triggered again.

So somehow the global zoom level changes a parameter how the preview image is generated.

**Comment by vstirbu** [comment]
I've tried the sequence on Mac and it does not behave the same. I still get the overflow.
