### ISSUE TITLE
Support for gitGraph

### ISSUE THREAD

**Issue by apetitbois** [vstirbu/vscode-mermaid-preview#78]
### Expected behaviour

```mermaid
gitGraph:
options
{
  "nodeSpacing": 150,
  "nodeRadius": 10
}
end
  commit
  branch newbranch
  checkout newbranch
  commit
  commit
  checkout master
  commit
  commit
  merge newbranch
```

This does not render. But if I generate the PDF/HTML from a browser, this actually renders fine.

This is what is seen in the preview:
![preview](https://user-images.githubusercontent.com/16504932/59355753-98cda180-8cf5-11e9-99c3-dc7354564aea.PNG)

This is what is seen when rendered as HTML
![rendered](https://user-images.githubusercontent.com/16504932/59355779-a6832700-8cf5-11e9-8d35-1e349f177498.PNG)

**Comment by vstirbu** [comment]
The plugin should use the latest mermaid from npm registry. Which version of mermaid are you using in the browser?

**Comment by apetitbois** [comment]
```
<script type="text/javascript" src="file:///C:\Users\[...]\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.4.1\node_modules\@shd101wyy\mume\dependencies\mermaid\mermaid.min.js" charset="UTF-8"></script>
```

**Comment by vstirbu** [comment]
I've tried your example and this is what I get:

<img width="1721" alt="Screenshot 2019-06-13 at 9 47 33" src="https://user-images.githubusercontent.com/1288047/59410018-689f0500-8dc0-11e9-8507-6c57eafb8d7c.png">

There are some problems with the rendering after the first draw of the diagram but it is not the problem that you report. Your snippet points to `shd101wyy.markdown-preview-enhanced`, which is another plugin.

**Comment by vstirbu** [comment]
I've done further investigation on this type of diagram and the results are not encouraging. 

`gitGraph` is still experimental in mermaid and the resulting SVG lacks elements that would facilitate handling it properly in this plugin:

* no way to detect the `width` of the diagram. mermaid output just says `100%`.
* while the first draw works fine, re-rendering the diagram has some nasty side effects as the paths are rendered somewhere far on the right (no way to have live editing)

Considering this I propose to close this issue and come back when the mermaid support matures.
