### ISSUE TITLE
Incorrect render when using "activate" command

### ISSUE THREAD

**Issue by emilekberg** [vstirbu/vscode-mermaid-preview#79]
### Expected behaviour

```mermaid
sequenceDiagram
    participant A as A
    participant B as B
    participant C as C

    A->>B: Call
    activate B
        B->>C: Call
        activate C
        C->>B: Done
        deactivate C
    deactivate B
    B->>A: Done

    
```

### Actual behaviour

![image](https://user-images.githubusercontent.com/4872503/59760938-bbcaf900-9293-11e9-8855-cd98474ce0b9.png)

Also if i remove the "as" it renders incorrectly

![image](https://user-images.githubusercontent.com/4872503/59760975-da30f480-9293-11e9-954c-35c1ea6f8475.png)

if i remove the `activate`and `deactivate` commands it looks correct.
![image](https://user-images.githubusercontent.com/4872503/59760703-36474900-9293-11e9-9810-bc48da3b628e.png)

**Comment by vstirbu** [comment]
I'm not able to replicate the described behaviour. Here is my result when embedding the diagram in a markdown file:

<img width="532" alt="Screenshot 2019-06-19 at 14 21 42" src="https://user-images.githubusercontent.com/1288047/59761566-d3a77a80-929d-11e9-92f2-a44c864b05ad.png">

Do you get any errors in the console?

**Comment by emilekberg** [comment]
Could it be OS related? i'm running windows. 
output>extensions does not give any errorsm if this is what you meant with the console.

**Comment by vstirbu** [comment]
Might be. I have not tested on Windows as I do not have access to such a machine.

Have you tried to reinstall the extension? It has quite large dependencies and that might be a problem.
