### ISSUE TITLE
Some font awesome icons is not working

### ISSUE THREAD

**Issue by robertahazinolx** [vstirbu/vscode-mermaid-preview#83]
### Expected behaviour

```mermaid
graph LR
  A -->|R| B{B}
  B --> C
  C -->|U| D[fa:fa-hand-paper D]
  D --> E
  D --> F[fa:fa-cog Consumer F]
```

The both `hand-paper` and `cog` icons should appear (screenshot captured from Mermaid Live Editor): 
![Screenshot 2019-07-03 at 16 04 17](https://user-images.githubusercontent.com/48800624/60602822-72f36400-9dac-11e9-986f-58a6553755d8.png)

### Actual behaviour
Only the `cog` icon appears (screenshot captured from Mermaid Preview extension).
![Screenshot 2019-07-03 at 16 07 31](https://user-images.githubusercontent.com/48800624/60602977-c4035800-9dac-11e9-8dc8-16ae1c448430.png)

It was noticed that this weird behaviour occurs for all icons with composite names.

**Comment by vstirbu** [comment]
Thanks for bringing this up. It seems that the online editor uses a newer font awesome version.

The upgrade path from 4 to 5 is not that clear so I would appreciate some help in this area...

**Comment by vstirbu** [comment]
There is a related issue on mermaid (knsv/mermaid/issues/830). The plugin already includes the file but does not seem to work in our case.
