### ISSUE TITLE
Preview does not update when transitioning from parse error to valid syntax

### ISSUE THREAD

**Issue by Pugio** [vstirbu/vscode-mermaid-preview#91]
As soon as I enter in any kind of invalid Mermaid syntax, the Preview pane clears and refuses to display anything else thereafter.

### Expected behaviour

```mermaid
graph TD
A
```

If I then type:

```mermaid
graph TD
A--
```

The pane clears.

### Actual behavior
```mermaid
graph TD
A-->B
```

![image](https://user-images.githubusercontent.com/286180/68558359-2a039880-048d-11ea-9a93-cb7b43ea49d5.png)

* Preview mode: Mermaid
* Theme used: dark
VS Code: Version: 1.40.0
Mermaid Preview Version: v1.2.0
OS X 10.13.6

**Comment by Pugio** [comment]
Upon further inspection, it also seems as though the Mermaid renderer is also receiving the source text with all newlines stripped out:

![image](https://user-images.githubusercontent.com/286180/68558637-2de3ea80-048e-11ea-99ba-84b79a5cc5b1.png)

**Comment by vstirbu** [comment]
Thanks for reporting this behaviour. I'm able to reproduce it.

(I'm a bit overloaded now, so it will take some time to work on a fix...)
