### ISSUE TITLE
Minimap Overlaps diagram

### ISSUE THREAD

**Issue by sebinjohn** [vstirbu/vscode-mermaid-preview#95]
### Expected behaviour
The minimap is restricted to a small space

```mermaid
graph LR
   subgraph a
      A --> B
      B --> C
      A --> C
   end
   D --> A
   A --> B
   B --> A
   A --> D
   D --> A
```

### Actual behaviour

Minimap creeps into the actual diagram space

Include:
![Screen Shot 2019-12-10 at 4 55 35 pm](https://user-images.githubusercontent.com/7448659/70499828-1f145480-1b6e-11ea-9139-169fd685ecf4.png)

Preview mode: Mermaid
Theme used: dark

I know a similar issue is already fixed in https://github.com/vstirbu/vscode-mermaid-preview/issues/66

Can you please add an option to turn off minimap during preview

**Comment by minemax-ua** [comment]
I have a similar issue. Can I turn the minimap off completely?

**Comment by vstirbu** [comment]
The `minimap` visibility is controlled via `mermaid.vscode.minimap` configuration.

* `true` for visible
* `false` for hidden
