### ISSUE TITLE
Azure Devops Syntax

### ISSUE THREAD

**Issue by drewkg** [vstirbu/vscode-mermaid-preview#96]
The Azure DevOps wiki engine expects mermaid to be marked with the syntax of 

::: mermaid

:::
instead of the markdown syntax of 

```mermaid
Include the mermaid diagram
```
Is there any plan to support preview of this syntax?

**Comment by vstirbu** [comment]
Thanks! Added to backlog.

**Comment by jantielens** [comment]
Would be awesome! (also see this thread: https://developercommunity.visualstudio.com/idea/826044/mermaid-use-the-code-blog-identifier-istead-of-a-c.html?childToView=947222#comment-947222)

**Comment by jantielens** [comment]
Btw, the [findDiagram](https://github.com/vstirbu/vscode-mermaid-preview/blob/6b8a63e4665c73bfd497d410f439af3f11d4c0f0/lib/find-diagram.js#L36) function already seems to be looking for `:::mermaid`, but I think the syntax is `::: mermaid` (with a space in between, see [docs](https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#add-mermaid-diagrams-to-a-wiki-page)).

**Comment by vstirbu** [comment]
Thanks for the tip with the discussion!

The space in between looks very weird and does not fit any use pattern that I've heard of in any markdown flavours... but this is the situation with Azure DevOps 😷

**Comment by vstirbu** [comment]
fixed in v1.5.1
